import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import { readFile } from 'node:fs/promises';
import { buildLanguages } from './scripts/build-languages.mjs';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';
const nodeBuiltins = builtinModules.flatMap(moduleName =>
    moduleName.startsWith('node:') ? [moduleName] : [moduleName, `node:${moduleName}`]
);

const context = await esbuild.context({
    banner: {
        js: banner
    },
    plugins: [
        {
            name: 'language-assets',
            setup(build) {
                let watchFiles = [];
                build.onStart(async () => {
                    watchFiles = await buildLanguages();
                });
                build.onLoad({ filter: /[\\/]i18n[\\/]localeMetadata\.ts$/ }, async ({ path }) => ({
                    contents: await readFile(path, 'utf8'),
                    loader: 'ts',
                    watchFiles
                }));
                build.onEnd(result => {
                    if (!prod || result.errors.length > 0) return;
                    const bytes = result.metafile.outputs['main.js'].bytes;
                    console.log(`main.js: ${bytes.toLocaleString('en-US')} bytes (${(bytes / 1000000).toFixed(2)} MB)`);
                    if (bytes >= 5000000) return { errors: [{ text: 'main.js reaches the 5 MB Obsidian Sync Standard limit' }] };
                    if (bytes >= 4500000) return { warnings: [{ text: 'main.js exceeds the 4.5 MB size warning threshold' }] };
                });
            }
        }
    ],
    metafile: true,
    entryPoints: ['src/main.ts'],
    bundle: true,
    define: {
        'process.env.NODE_ENV': prod ? '"production"' : '"development"'
    },
    external: [
        'obsidian',
        'electron',
        '@codemirror/autocomplete',
        '@codemirror/collab',
        '@codemirror/commands',
        '@codemirror/language',
        '@codemirror/lint',
        '@codemirror/search',
        '@codemirror/state',
        '@codemirror/view',
        '@lezer/common',
        '@lezer/highlight',
        '@lezer/lr',
        ...nodeBuiltins
    ],
    format: 'cjs',
    target: 'es2022',
    charset: 'utf8',
    logLevel: 'info',
    sourcemap: prod ? false : 'inline',
    treeShaking: true,
    outfile: 'main.js',
    minify: prod
});

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}
